name: nfl-survivor-2025
channels:
  - defaults
dependencies:
  - python=3.11
  - pandas
  - numpy
  - requests
  - beautifulsoup4
  - lxml
  - matplotlib
  - seaborn
  - jupyter
  - ipykernel
  - ipywidgets
  - pip
  - pip:
      - python-dotenv
